[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/tuankhoin/COMP30027-Practical-Solutions/blob/main/2022/Week%202.ipynb)

In [1]:
%%html
<marquee style='width: 50%; color: white; font-size:35px;' scrollamount=20><b>WELCOME TO COMP30027!</b></marquee>

## Boring stuff
- My full name is Tuan Khoi Nguyen, and you can call me Khoi
- Master of Engineering (Mechatronics)
- Email: `tuankhoi@unimelb.edu.au` || `tuankhoin@student.unimelb.edu.au`

## Facts
- May swear during teaching (sorry in advance)
- Can recommend good food in Footscray (Nguyen gang)
- Hobbies: a bit of hiking and photography


### The University of Melbourne, School of Computing and Information Systems
# COMP30027 Machine Learning, 2022

## Week 2 - Introduction
- Jupyter Notebook
- `numpy`

### What are we using?
- Python 3.x
- Jupyter Notebook

Just so?
- `numpy`
- `pandas`
- `matplotlib`
- `scikit-learn`
- `scipy`

### Do you even Notebook?
- `pip`/`apt-get`/`brew`
- Anaconda
- VSCode & friends
- Google Colab
- What else?

## Cells

Notebooks are made up cells: *markdown cells* and *code cells*. 

Markdown cells can contain text, tables, images, equations, etc. 
(see the Markdown guide under the _Help_ menu for more info). 

Next are some code cells. 
You can evaluate them individually, using the <button class='btn btn-default btn-xs'><i class="icon-step-forward fa fa-step-forward"></i></button> button or by hitting `<CTRL>+<ENTER>`. 
Often, you'll want to run all cells in the notebook, or below a certain point. The functions for doing this are in the _Cell_ menu.

`<Ctrl + Enter>`: Run the cell

`<ESC>` + ...
- `A`: New cell above
- `B`: New cell below
- `M`: Markdown mode
- `Y`: Code mode
- `D D`: Delete
- `L`: Show line numbers

More? Google 'Jupyter notebook shortcuts'

In [2]:
message = "Wassup world!"
print(message)

Wassup world!


Please ensure that the scipy, numpy, matplotlib, and sklearn packages are installed (although we won’t be
using the latter two today).

In [3]:
import scipy
import numpy as np 
import matplotlib as mpl
import sklearn

(You might wish to examine the installation instructions at http://scipy.org/install.html
if you are considering using your local machine.)

## NumPy Basics

The main numpy object is a so-called “homogeneous multidimensional array” — note that this is a little less flexible than using a list or tuple, but it allows mathematical operations to be performed much faster. (And we’ll be doing a fair bit of number-crunching this semester, so this is an important property.) The following is an introduction to NumPy functions and properties.

### Creating Arrays

In [4]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype = float)
c = np.array([[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]], dtype = int)

In [5]:
np.arange(0, 10)     # array of evenly spaced values




np.linspace(0,9,10).astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((2, 3))     # array of zeros with the given shape

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones(2)           # array of ones with the given shape

array([1., 1.])

In [8]:
np.empty((2, 3))     # empty array (arbitrary values)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.eye(3)                          # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.full((2, 3), 3)   # fill new array with given shape

array([[3, 3, 3],
       [3, 3, 3]])

### Inspecting an array

In [11]:
b.size               # number of elements in the array

10

In [12]:
b.ndim               # number of dimensions

2

In [13]:
b.shape              # lengths of each dimension

(2, 5)

In [14]:
b.dtype              # data type of array elements

dtype('float64')

### Numpy Basic operations


Numpy supports vector (and matrix) operations,like addition, subtraction, and scalar multiplication.

You need to be very, very careful about manipulating arrays of different sizes. numpy typically won’t throw exceptions. Instead, it will do "something": that something might be very intelligent, like automatically increasing the dimensionality of the smaller array to match the larger array — but if you aren’t expecting it, the errors can be very difficult to find.

In [15]:
a1 = np.array([0,1,2,3,4])
a2 = np.array([1,3,-2,0,4])

In [16]:
print(a1 + a2)                # element-wise addition (or np.add)
print(a1 - a2)                # element-wise subtraction (or np.subtract)
print(a1 * a2)                # element-wise multiplication (or np.multiply)
print(a1 / a2)                # element-wise division (or np.divide)

[1 4 0 3 8]
[-1 -2  4  3  0]
[ 0  3 -4  0 16]
[ 0.          0.33333333 -1.                 inf  1.        ]


C:\Users\HP OMEN 15\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [17]:
b.sum()              # sum elements
b.min()              # minimum element
b.max()              # maximum element
b.mean()             # mean of elements
a == a               # element-wise comparison

array([ True,  True,  True,  True,  True])

#### Question 1
How can we add (element-wise) arrays `b` and `c`? 

In [18]:
print(b)
print(c)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


#### Answer
We cannot! ;) The two arrays `b` and `c` have different shapes. `b.shape` is `(2, 5)`, while `c.shape` is `(5,2)` so none of the basic numpy operations (addition, subtraction, and scalar multiplication) can happen between them.   

In [19]:
# b+c --> ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

#### Question 2
What do you think would be the result of comparision `b < 2`? How about `a1 = a2`?

In [20]:
b < 2                   # element-wise comparison

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [21]:
a1 == a2                # element-wise comparison

array([False, False, False, False,  True])

#### Question 3
How can we check whether arrays have the same shape and elements?

In [22]:
np.array_equal(a, b)  # check whether arrays have the same shape and elements

False

Bonus: What if we know that `a.shape == b.shape` ?

In [23]:
(a==b).all()
np.allclose(a,b)    # float comparison

False

### Using Numpy arrays

Numpy arrays can be indexed, sliced, and iterated over, similarly to lists. 

#### Exercise 1
Write a function to calculate the **Euclidean distance** between $\vec{a}$ and $\vec{b}$. 

\begin{align}
    E_d(\vec{a},\vec{b})= \sqrt{\sum_{i=1}^n (a_i-b_i)^2}
\end{align}

In [24]:
# Original solution
def my_euclidean_dist(a, b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return np.sqrt(sum([(a[i]-b[i])*(a[i]-b[i]) for i in range(len(a))]))

def my_euclidean_dist_2(a, b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return sum((a-b)**2)**0.5

Use this function to calculate the eculadian Distance between `a1` and `a2`.

In [25]:
print(my_euclidean_dist(a1, a2))
print(my_euclidean_dist_2(a1, a2))

5.477225575051661
5.477225575051661


### Numpy and Matrices

Matrices can be made in numpy by wrapping a list of lists. For example the matrices M and N can be modeled in Numpy by using the following code.
$$
\begin{align}
    \mathbf{M} = \begin{pmatrix} 
        1 & 2 & 3 \\ 4 & 2 & 1 \\ 6 & 2 & 0 
    \end{pmatrix} 
    \quad \text{and} \quad 
    \mathbf{N} = \begin{pmatrix} 
        0 & 3 & 1 \\ 1 & 1 & 4 \\ 2 & 0 & 3 
    \end{pmatrix}
\end{align}
$$

In [26]:
M = np.array([[1,2,3],[4,2,1],[6,2,0]])
N = np.array([[0,3,1],[1,1,4],[2,0,3]])

You can use Numpy to perform all kind of **Linear Algebra** operations on these matrices. Such as:

In [28]:
np.transpose(M)                    # reverse the Matrix M



M.T

array([[1, 4, 6],
       [2, 2, 2],
       [3, 1, 0]])

In [29]:
np.dot(M,N)                        # Calculate the dot product of M and N (Does it?)



M @ N # (Python 3.5+)

array([[ 8,  5, 18],
       [ 4, 14, 15],
       [ 2, 20, 14]])

In [30]:
np.linalg.inv(M)                   # matrix inverse



np.matrix(M).I

matrix([[ 1. , -3. ,  2. ],
        [-3. ,  9. , -5.5],
        [ 2. , -5. ,  3. ]])

In [31]:
np.reshape(M,9)                    # reshape the matrix to a 1D row

array([1, 2, 3, 4, 2, 1, 6, 2, 0])

In [32]:
arr = np.reshape(range(9),(3,3))   # reshape the 1D row (range(9)) to a 3x3 matrix
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
np.delete(arr, 0, 1)                # remove the first column of the matrix

array([[1, 2],
       [4, 5],
       [7, 8]])

In [34]:
np.delete(arr, 2, 0)                # remove the third row of the matrix

array([[0, 1, 2],
       [3, 4, 5]])

#### Exercise 2

Write a function that calculates the dot product between two vectors: A · B = $\sum_{i} a_ib_i$. Find the between  first row of matrix `M` and the first column of matrix `N`.  

In [35]:
# Original solution
def my_dot(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return sum([a[i]*b[i] for i in range(len(a))])

def my_dot_2(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return sum(a*b)

def my_dot_3(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return np.einsum('i,i->',a,b)

In [36]:
row = M[0]          #copies the first row from Matric M
column = N[:,0]     #copies the first column from Matric N
print(my_dot(row,column))
print(my_dot_2(row,column))
print(my_dot_3(row,column))

8
8
8


#### Exercise 3
Write a short script to compare:
1. M * N and np.dot(M, N)
2. N * M and np.dot(N, M)
3. M * M and M**2 and np.dot(M, M)

In [37]:
print("M*N\n",M*N)
print("M.N\n",M @ N)
print("N*M\n",N*M)
print("N.M\n",N @ M)
print("M*M\n",M*M)
print("M**2\n",M**2)
print("M.M\n",M @ M)

M*N
 [[ 0  6  3]
 [ 4  2  4]
 [12  0  0]]
M.N
 [[ 8  5 18]
 [ 4 14 15]
 [ 2 20 14]]
N*M
 [[ 0  6  3]
 [ 4  2  4]
 [12  0  0]]
N.M
 [[18  8  3]
 [29 12  4]
 [20 10  6]]
M*M
 [[ 1  4  9]
 [16  4  1]
 [36  4  0]]
M**2
 [[ 1  4  9]
 [16  4  1]
 [36  4  0]]
M.M
 [[27 12  5]
 [18 14 14]
 [14 16 20]]


You can probably see that the multiplication (and exponentiation) operation happens element-wise, namely:
$MN[i][j] = M[i][j] * N[i][j]$

This is actually convenient in certain contexts, but is certainly not how we typically wish to multiply matrices!

#### Exercise 4
Consider the matrix **T1** as
$$
\begin{align}
    \mathbf{T1} = \begin{pmatrix} 
        1 & 2 & 3 \\ 4 & 5 & 6 
    \end{pmatrix} 
\end{align}
$$
and arrays T2 & T3 as **T2** = `<7, 8, 9>` **T3** = `<10, 20, 30>`. Write a script to do the following:
1. add **T2** as the third row to **T1**; 
2. add **T3** as the forth column to the result matrix

In [38]:
T1 = np.reshape(range(1,7), (2,3))
T2 = np.array([range(7,10)])
T3 = np.array([[10, 20, 30]])

R1 = np.concatenate((T1, T2), axis=0)
print("R1\n",R1)

R2 = np.concatenate((R1, T3.T), axis=1)
print("R2\n",R2)

R1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
R2
 [[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


## Getting Help
Confused about a particular function / method? Putting a question mark `<?>` after the object in question will return the docstring.

In [39]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the ``normal`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Out

## Interrupting/restarting the kernel

Code is run in the kernel process. You can interrupt the kernel by pressing the stop button <button class='btn btn-default btn-xs'><i class='icon-stop fa fa-stop'></i></button> in the toolbar. Try it out below.

In [40]:
import time
time.sleep(10)

Occassionally you may want to restart the kernel (e.g. to clear the namespace). You can do this by pressing the <button class='btn btn-default btn-xs'><i class='icon-epeat fa fa-repeat'></i></button> button in the toolbar. You can find more options under the _Kernel_ menu.